config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  resources :users
  resources :blogs
  resources :comments
  resources :relationships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title,  presence: true, length: { maximum: 30, minimum: 5 }
  validates :body, presence: true, length: { maximum: 200, minimum: 10 }

  scope :ordered_by_date, ->{order created_at: :desc}
  scope :user_id_in, ->(following_ids, id){where(
    "user_id IN (:following_ids) OR user_id = :user_id",
    following_ids: following_ids, user_id: id)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  scope :ordered_by_date, ->{order created_at: :desc}

  validates :text,  presence: true, length: { maximum: 100, minimum: 3 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50, minimum: 4 }
  validates :email, presence: true, length: { maximum: 50, minimum: 6 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :blogs
  has_many :comments
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_secure_password

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = self.class.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false unless remember_digest
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def current_user? user
    self == user
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please login"
      redirect_to login_url
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]
  before_action :find_blog, except: [:index, :new, :create]

  def index
    @blogs = Blog.all.ordered_by_date.page params[:page]
  end

  def new
    @blog = current_user.blogs.build
  end

  def create
    @blog = current_user.blogs.build blog_params
    if @blog.save
      flash[:success] = "Blog successfully created"
      redirect_to root_url
    else
      render "blogs/new"
    end
  end

  def show
    @blog = Blog.find_by id: params[:id]
    @comments = @blog.comments.ordered_by_date.page params[:page]
    @comment = @blog.comments.build
  end

  private
  def blog_params
    params.require(:blog).permit :title, :body
  end

  def find_blog
    @blog = Blog.find_by id: params[:id]
    return if @blog
    flash[:danger] = "Something went wrong"
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new comments_param
    @comment.user = current_user
    @comment.blog = Blog.find_by id: params[:comment][:blog_id]

    if @comment.save
      respond_to do |format|
        format.html { redirect_to @comment.blog }
        format.js
      end
    else
      flash[:notice] = "Something went wrong"
    end
  end

  def index
  end

  private
  def comments_param
    params.require(:comment).permit :text, :blog
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = "Login successfuly"
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user
      @blogs = Blog.user_id_in(current_user.following_ids, current_user.id).ordered_by_date.page params[:page]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = "Welcome to app"
      redirect_to root_url
    else
      flash[:danger] = "Something went wrong"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = "Something went wrong"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<div class="col-md-12">
  <h2>Blogs</h2>
</div>

<div class="row justify-content-center">
  <div class="list-group col-md-8 ">
    <% @blogs.each do |blog| %>
      <%= link_to blog, class:"list-group-item list-group-item-action flex-column align-items-start" do %>
        <div class="d-flex w-100 justify-content-between">
          <h3 class="mb-1"><%= blog.title %></h3>
          <small><%= time_ago_in_words(blog.created_at) %> ago</small>
        </div>
        <p class="mb-1"><%= blog.body %></p>
        <small>by <%= blog.user.name %>.</small>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row justify-content-center">
<%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-md-12">
  <h2>Blogs</h2>
</div>
<%= form_for @blog, class:"form-group" do |f| %>
  <% if @blog.errors.any? %>
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.text_area :body, placeholder: "Body", class:"form-control" %>
  </div>
  <%= f.submit "Create", class: "btn btn-warning form-control" %>

<% end %>

app/views/blogs/show.html.erb
<h1>Title: <%= @blog.title %></h1>
<h3>Body: <%= @blog.body %></h3>
<br/><br/><br/><br/>


<% if current_user %>
  Your thougth?
  <div id="comment_form">
    <%= render "comments/form", comment: @comment, blog: @blog %>
  </div>
<% end %>
<br/>
  <h4>Comments</h4>

<div id="comment_list">
  <%= render "comments/comments", comments: @comments %>
</div>
<div id="paginate_comments">
  <%= render "comments/paginate_comments", comments: @comments, blog_id: @blog.id %>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comm| %>
  <div class="card">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= comm.text %>.</p>
        <footer class="blockquote-footer"><%= comm.user.name %></footer>
      </blockquote>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for comment, remote: true, class:"form-group" do |f| %>
  <%= f.text_area :text, class:"form-control" %>
  <%= f.hidden_field :blog_id, value: blog.id %>
  <%= f.submit "Send", class:"btn btn-warning form-control" %>
<% end %>

app/views/comments/_paginate_comments.html.erb
<%= paginate comments, params: {controller: 'blogs', action: 'show', id: blog_id} %>

app/views/comments/create.js.erb
$('#comment_form form textarea').val('');
$("#comment_list").html("<%= escape_javascript(render('comments/comments', comments: @comment.blog.comments.ordered_by_date.page(1))) %>");
// <% @comments = @comment.blog.comments.ordered_by_date.page %>
$("#paginate_comments").html("<%= escape_javascript(render('comments/paginate_comments', comments: Blog.find_by(id: params[:comment][:blog_id]).comments.ordered_by_date.page(1), blog_id: params[:comment][:blog_id] )) %>")

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Blogs", blogs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>


      <% unless logged_in? %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", register_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Create blog", new_blog_path, class:"dropdown-item" %>
            <%= link_to "Logout", logout_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntryBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/static_pages/home.html.erb
Welcome
<% if current_user %>
  <div class="row justify-content-center">
    <div class="list-group col-md-8 ">
      <% @blogs.each do |blog| %>
        <%= link_to blog, class:"list-group-item list-group-item-action flex-column align-items-start" do %>
          <div class="d-flex w-100 justify-content-between">
            <h3 class="mb-1"><%= blog.title %></h3>
            <small><%= time_ago_in_words(blog.created_at) %> ago</small>
          </div>
          <p class="mb-1"><%= blog.body %></p>
          <small>by <%= blog.user.name %>.</small>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
  <%= paginate @blogs %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true, class:"form-group") do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class:"btn btn-primary btn-lg" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
  html: { method: :delete }, remote: true, class:"form-group") do |f| %>
  <%= f.submit "Unfollow", class:"btn btn-primary btn-lg" %>
<% end %>

app/views/users/index.html.erb
<div class="col-md-12">
  <h2>User List</h2>
</div>
<div class="row justify-content-center">
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Register</h1>
<div class="col-md-6 offset-md-3">
  <%= form_for @user, html: {class: "form-group"} do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <%= t "error_form", err_num: @user.errors.count %>.
        </div>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <%= f.submit "Register", class: "btn btn-warning form-control" %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>User: <%= @user.name %></h1>
<h1>Email: <%= @user.email %></h1>
<% if current_user %>
  <h2>Please scroll down to see Follow/Unfollow button :) </h2>
  <br/>
  <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  <% unless @user.current_user? current_user %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
        <%= render "unfollow" %>
      <% else %>
        <%= render "follow" %>
      <% end %>
    </div>
  <% end %>
  <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  Asd
<% end %>